/// AppStrings — centralized i18n.
class AppStrings {
  const AppStrings._(this._map, this.langCode);

  factory AppStrings.of(String lang) {
    final map = _allLanguages[lang] ?? _allLanguages['en']!;
    return AppStrings._(map, lang);
  }

  final Map<String, String> _map;
  final String langCode;

  String _t(String k) => _map[k] ?? k;

  // ── Navigation ─────────────────────────────────────────────────────────────
  String get appNameShort   => _t('appNameShort');
  String get navHome         => _t('navHome');
  String get navLiveTV      => _t('navLiveTV');
  String get navMovies      => _t('navMovies');
  String get navSeries      => _t('navSeries');
  String get navFavorites   => _t('navFavorites');
  String get navSearch      => _t('navSearch');
  String get navSettings    => _t('navSettings');

  // ── Common ─────────────────────────────────────────────────────────────────
  String get retry          => _t('retry');
  String get cancel         => _t('cancel');
  String get save           => _t('save');
  String get delete         => _t('delete');
  String get update         => _t('update');
  String get load           => _t('load');
  String get connect        => _t('connect');
  String get close          => _t('close');
  String get back           => _t('back');
  String get results        => _t('results');
  String get noResultsFound   => _t('noResultsFound');
  String get loading        => _t('loading');
  String get nowLive        => _t('nowLive');

  // ── Playlist ───────────────────────────────────────────────────────────────
  String get noPlaylistSelected  => _t('noPlaylistSelected');
  String get addPlaylistHint     => _t('addPlaylistHint');
  String get goToSettings        => _t('goToSettings');
  String get addPlaylist         => _t('addPlaylist');
  String get noPlaylistYet       => _t('noPlaylistYet');
  String get savedPlaylists      => _t('savedPlaylists');
  String get noPlaylistsAdded    => _t('noPlaylistsAdded');
  String get demoDownloadHint    => _t('demoDownloadHint');
  String get playlistLoaded      => _t('playlistLoaded');
  String get playlistExists      => _t('playlistExists');
  String get playlistExistsQ     => _t('playlistExistsQ');
  String get playlistDeleted     => _t('playlistDeleted');
  String get playlistDeleteQ     => _t('playlistDeleteQ');
  String get playlistRename      => _t('playlistRename');
  String get playlistSelected    => _t('playlistSelected');
  String get enterM3uUrl         => _t('enterM3uUrl');
  String get playlistName    => _t('playlistName');
  String get server          => _t('server');
  String get username        => _t('username');
  String get password        => _t('password');
  String get channelsSaved   => _t('channelsSaved');
  String get done            => _t('done');
  String get error           => _t('error');
  String get channels        => _t('channels');
  String get fillAllFields   => _t('fillAllFields');
  String get validating      => _t('validating');
  String get loaded          => _t('loaded');
  String get selectAFile     => _t('selectAFile');
  String get reading         => _t('reading');
  String get local           => _t('local');
  String get newName         => _t('newName');
  String get updating        => _t('updating');
  String get updated         => _t('updated');
  String get import          => _t('import');
  String get channelsShort   => _t('channelsShort');
  String get demoDownloadPrompt => _t('demoDownloadPrompt');
  String get download        => _t('download');
  String get continueWatching => _t('continueWatching');
  String get recentlyAdded    => _t('recentlyAdded');
  String get discover         => _t('discover');

  // ── Content ────────────────────────────────────────────────────────────────
  String get noMoviesFound  => _t('noMoviesFound');
  String get noSeriesFound  => _t('noSeriesFound');
  String get continueWatch  => _t('continueWatch');
  String get favorites      => _t('favorites');
  String get noFavorites     => _t('noFavorites');
  String get searchHint     => _t('searchHint');
  String get typeToSearch   => _t('typeToSearch');
  String get liveTv         => _t('liveTv');
  String get movies         => _t('movies');
  String get series         => _t('series');

  String get episodes          => _t('episodes');
  String get similarContent     => _t('similarContent');

  String get exitConfirmTitle   => _t('exitConfirmTitle');
  String get exitConfirmMsg     => _t('exitConfirmMsg');
  String get yes               => _t('yes');
  String get no                => _t('no');

  String get errorUrlTitle      => _t('errorUrlTitle');
  String get errorUrlMsg        => _t('errorUrlMsg');
  String get playlistLoadedTitle => _t('playlistLoadedTitle');
  String get playlistLoadedMsg   => _t('playlistLoadedMsg');
  String get activateNow        => _t('activateNow');

  // ── EPG ────────────────────────────────────────────────────────────────────
  String get epgNoData      => _t('epgNoData');
  String get epgAddSource   => _t('epgAddSource');
  String get epgNeverSynced => _t('epgNeverSynced');
  String get epgSyncing     => _t('epgSyncing');
  String get epgUpdate      => _t('epgUpdate');
  String get epgUpdated     => _t('epgUpdated');
  String get epgFirstSyncPrompt => _t('epgFirstSyncPrompt');
  String get epgUpdateRecommended => _t('epgUpdateRecommended');
  String epgLastSync(int days) =>
      (_map['epgLastSync'] ?? 'EPG last updated: {days} days ago').replaceAll('{days}', '$days');
  String remMinutes(int minutes) =>
      (_map['remMinutes'] ?? '{minutes} min left').replaceAll('{minutes}', '$minutes');
  String duration(int minutes) =>
      (_map['duration'] ?? '{minutes} min').replaceAll('{minutes}', '$minutes');
  String get ending           => _t('ending');
  String get channel          => _t('channel');

  // ── Player ─────────────────────────────────────────────────────────────────
  String get audioTrack       => _t('audioTrack');
  String get subtitles        => _t('subtitles');
  String get subtitlesOff     => _t('subtitlesOff');
  String get streamError      => _t('streamError');
  String get streamErrorMsg   => _t('streamErrorMsg');
  String get channelInfo      => _t('channelInfo');
  String get movieInfo        => _t('movieInfo');
  String get epgTab           => _t('epgTab');
  String get infoTab          => _t('infoTab');
  String get noMovieInfo      => _t('noMovieInfo');
  String get added            => _t('added');
  String get removed          => _t('removed');
  String get category         => _t('category');
  String get type             => _t('type');
  String get quality          => _t('quality');
  String get country          => _t('country');
  String get season           => _t('season');
  String get episode          => _t('episode');
  String get audio            => _t('audio');
  String get all              => _t('all');
  String get aspectFit        => _t('aspectFit');
  String get aspect169        => _t('aspect169');
  String get aspect43         => _t('aspect43');
  String get aspectFill       => _t('aspectFill');
  String get aspectZoom       => _t('aspectZoom');
  String get addedToFav       => _t('addedToFav');
  String get removedFromFav   => _t('removedFromFav');
  String get screenRatio      => _t('screenRatio');
  String get off              => _t('off');
  String get favoritesShort   => _t('favoritesShort');
  String get guideChannel     => _t('guideChannel');
  String get guideSeek        => _t('guideSeek');
  String get guideVolume      => _t('guideVolume');
  String get checkingConnection => _t('checkingConnection');
  String get retryWithOk       => _t('retryWithOk');
  String get attempt           => _t('attempt');
  String get streamErrorDetailed => _t('streamErrorDetailed');
  String get sleepTimer       => _t('sleepTimer');
  String get noNetwork        => _t('noNetwork');
  String get playbackError    => _t('playbackError');
  String get decoderSuggestion => _t('decoderSuggestion');
  String get decoderMode      => _t('decoderMode');
  String get hwDecoder        => _t('hwDecoder');
  String get swDecoder        => _t('swDecoder');
  String get autoDecoder      => _t('autoDecoder');
  String get decoderAuto => _t('autoDecoder');
  String get decoderHw   => _t('hwDecoder');
  String get decoderSw   => _t('swDecoder');

  // ── Settings ───────────────────────────────────────────────────────────────
  String get settingsTitle    => _t('settingsTitle');
  String get about            => _t('about');
  String get developer        => _t('developer');
  String get tabM3U           => _t('tabM3U');
  String get tabXtream        => _t('tabXtream');
  String get tabLocal         => _t('tabLocal');
  String get importing        => _t('importing');
  String get connecting       => _t('connecting');
  String get downloadingDots  => _t('downloadingDots');
  String get parsing          => _t('parsing');
  String get selectM3UFile    => _t('selectM3UFile');
  String get localLoaded      => _t('localLoaded');
  String get langTitle        => _t('langTitle');
  String get syncingData      => _t('syncingData');
  
  String get setupWizard      => _t('setupWizard');
  String get setupWizardSub   => _t('setupWizardSub');
  String get addM3uTitle      => _t('addM3uTitle');
  String get addXtreamTitle   => _t('addXtreamTitle');
  String get appAndListMgmt   => _t('appAndListMgmt');
  String get newPlaylistAdd   => _t('newPlaylistAdd');
  String get actions          => _t('actions');
  String get version          => _t('version');
  String get checkUpdates     => _t('checkUpdates');
  String get checkingUpdates  => _t('checkingUpdates');
  String get upToDate         => _t('upToDate');
  String get active           => _t('active');
  String get selectSource     => _t('selectSource');
  String get m3uSub           => _t('m3uSub');
  String get xtreamSub        => _t('xtreamSub');
  String get localSub         => _t('localSub');
  String get altProtocolTry   => _t('altProtocolTry');
  String get httpsError       => _t('httpsError');
  String get m3uUrl           => _t('m3uUrl');
  String get playStore        => _t('playStore');
  String get github           => _t('github');
  String get rating           => _t('rating');
  String get year             => _t('year');
  String get alpha            => _t('alpha');
  String get noContentFound   => _t('noContentFound');
  String get forSmartTv       => _t('forSmartTv');

  String removeFavoriteQ(String name) =>
      (_map['removeFavoriteQ'] ?? 'Remove "{name}" from favorites?').replaceAll('{name}', name);

  String removeListQ(String name) =>
      (_map['removeListQ'] ?? 'Remove "{name}" from list?').replaceAll('{name}', name);

  String listSavedCount(int count) =>
      (_map['listSavedCount'] ?? '{count} Lists Saved').replaceAll('{count}', '$count');

  String playlistStats({required int tv, required int movie, required int series}) =>
      (_map['playlistStats'] ?? 'TV: {tv} | Movies: {movie} | Series: {series}')
          .replaceAll('{tv}', '$tv')
          .replaceAll('{movie}', '$movie')
          .replaceAll('{series}', '$series');
  
  // ── Folder Explorer ────────────────────────────────────────────────────────
  String get allDrives        => _t('allDrives');
  String get deviceFiles      => _t('deviceFiles');
  String get internalStorage  => _t('internalStorage');
  String get upFolder         => _t('upFolder');
  String get accessError      => _t('accessError');
  String get goInternal       => _t('goInternal');

  // ── Static Language Maps ───────────────────────────────────────────────────
  
  static final Map<String, Map<String, String>> _allLanguages = {
    'tr': _trMap,
    'en': _enMap,
    'de': _deMap,
    'fr': _frMap,
    'es': _esMap,
    'ru': _ruMap,
    'zh': _zhMap,
    'ar': _arMap,
  };

  static Map<String, String> getLanguageNames() => {
    'en': '🇺🇸 English',
    'tr': '🇹🇷 Türkçe',
    'de': '🇩🇪 Deutsch',
    'fr': '🇫🇷 Français',
    'es': '🇪🇸 Español',
    'ru': '🇷🇺 Русский',
    'zh': '🇨🇳 中文',
    'ar': '🇸🇦 العربية',
  };

  static const Map<String, String> _trMap = {
    'appNameShort':   'Aladin Player',
    'navHome':        'Ana Sayfa',
    'navLiveTV':      'Canlı TV',
    'navMovies':      'Filmler',
    'navSeries':      'Diziler',
    'navFavorites':   'Favoriler',
    'navSearch':      'Ara',
    'navSettings':    'Ayarlar',
    'retry':          'Tekrar Dene',
    'cancel':         'İptal',
    'save':           'Kaydet',
    'delete':         'Sil',
    'update':         'Güncelle',
    'load':           'Yükle',
    'connect':        'Bağlan',
    'close':          'Kapat',
    'back':           'Geri',
    'results':        'sonuç',
    'noResultsFound': 'Sonuç bulunamadı',
    'loading':        'Yükleniyor...',
    'nowLive':        'CANLI',
    'noPlaylistSelected': 'Playlist Seçilmedi',
    'addPlaylistHint':    'Ayarlar\'dan M3U playlist ekleyin',
    'goToSettings':       'Ayarlara Git',
    'addPlaylist':        '+ Playlist Ekle',
    'noPlaylistYet':      'Henüz playlist eklenmedi',
    'savedPlaylists':     'Kayıtlı Playlistler',
    'noPlaylistsAdded':   'Henüz playlist yok.',
    'demoDownloadHint':   'Demo — dokunarak indir',
    'playlistLoaded':     '✅ Playlist yüklendi!',
    'playlistExists':     'Mevcut Playlist',
    'playlistExistsQ':    'zaten var. Güncellensin mi?',
    'playlistDeleted':    'Silindi',
    'playlistDeleteQ':    'silinsin mi?',
    'playlistRename':     'Yeniden Adlandır',
    'playlistSelected':   'seçildi',
    'enterM3uUrl':        'Lütfen M3U URL giriniz',
    'playlistName':       'Playlist Adı',
    'server':             'Sunucu',
    'username':           'Kullanıcı',
    'password':           'Şifre',
    'channelsSaved':      'kanal kaydedildi',
    'done':               'Tamam',
    'error':              'Hata',
    'channels':           'kanal',
    'fillAllFields':      'Tüm alanları doldurun',
    'validating':         'Doğrulanıyor...',
    'loaded':             'yüklendi',
    'selectAFile':        'Dosya seçiniz',
    'reading':            'Okunuyor...',
    'local':              'Lokal',
    'newName':            'Yeni ad',
    'updating':           'güncelleniyor',
    'updated':            'güncellendi',
    'import':             'İçe Aktar',
    'channelsShort':      'kanal',
    'demoDownloadPrompt': 'Demo playlist henüz indirilmedi. Şimdi indirilsin mi?',
    'download':           'İndir',
    'continueWatching':   'Kaldığın Yerden',
    'recentlyAdded':      'Yeni Eklenenler',
    'discover':           'Yeni İçerikler Keşfet',
    'noMoviesFound':  'Film bulunamadı',
    'noSeriesFound':  'Dizi bulunamadı',
    'continueWatch':  '🕒 Kaldığın Yerden',
    'favorites':      '⭐ Favoriler',
    'noFavorites':    'Henüz favori eklenmemiş',
    'searchHint':     'Kanal, film, dizi ara...',
    'typeToSearch':   'Aramak için yazın',
    'liveTv':         'Canlı TV',
    'movies':         'Filmler',
    'series':         'Diziler',
    'episodes':       'Bölümler',
    'similarContent': 'Benzer İçerikler',
    'exitConfirmTitle': 'Çıkış Onayı',
    'exitConfirmMsg':   'Uygulamadan çıkmak istediğinize emin misiniz?',
    'yes':               'Evet',
    'no':                'Hayır',
    'errorUrlTitle':    'Bağlantı Hatası',
    'errorUrlMsg':      'Playlist yüklenemedi. Lütfen URL adresini kontrol edin. \n\nİpucu: "http://" yerine yanlışlıkla "https://" yazılmış olabilir veya adresin sonu eksik olabilir.',
    'playlistLoadedTitle': 'Yükleme Başarılı',
    'playlistLoadedMsg':   'Playlist başarıyla yüklendi. Şimdi aktif edip kanal listesine gitmek ister misiniz?',
    'activateNow':      'Şimdi Aktif Et',
    'epgNoData':      'EPG verisi bulunamadı',
    'epgAddSource':   'Ayarlar\'dan EPG güncelle',
    'epgNeverSynced': 'EPG hiç güncellenmedi',
    'epgLastSync':    'EPG son güncelleme: {days} gün önce',
    'epgSyncing':     'Güncelleniyor...',
    'epgUpdate':      'EPG Güncelle',
    'epgUpdated':     '✅ EPG güncellendi',
    'epgFirstSyncPrompt': 'EPG verilerini şimdi güncellemek ister misiniz?',
    'epgUpdateRecommended': 'Güncelleme önerilir',
    'remMinutes':     '{minutes} dk kaldı',
    'duration':       '{minutes} dk',
    'ending':         'bitiyor...',
    'channel':        'Kanal',
    'audioTrack':     'Ses Kanalı',
    'subtitles':      'Altyazı',
    'subtitlesOff':   'Kapalı',
    'streamError':    'Yayın Açılamadı',
    'streamErrorMsg': 'Bu yayın şu an kullanılamıyor. Farklı bir kaynak ya da daha sonra tekrar deneyin.',
    'channelInfo':    'Kanal Bilgisi',
    'movieInfo':      'Film/Dizi Bilgisi',
    'epgTab':         'Yayın Akışı',
    'infoTab':        'Bilgi',
    'noMovieInfo':    'Film/dizi bilgisi bulunamadı',
    'added':          'eklendi',
    'removed':        'çıkarıldı',
    'category':       'Kategori',
    'type':           'Tür',
    'quality':        'Kalite',
    'country':        'Ülke',
    'season':         'Sezon',
    'episode':        'Bölüm',
    'audio':          'Ses',
    'all':            'Tümü',
    'aspectFit':      'Sığdır',
    'aspect169':      '16:9',
    'aspect43':       '4:3',
    'aspectFill':     'Doldur',
    'aspectZoom':     'Zoom',
    'addedToFav':     'Favorilere eklendi',
    'removedFromFav': 'Favorilerden çıkarıldı',
    'screenRatio':    'Ekran Oranı',
    'off':            'Kapalı',
    'favoritesShort': 'Favori',
    'guideChannel':   '↕ Kanal Değiştir',
    'guideSeek':      '↔ İleri/Geri Sar',
    'guideVolume':    '↔ Ses Ayarla',
    'checkingConnection': 'Bağlantı/Sunucu kontrol ediliyor...',
    'retryWithOk':    'Yeniden denemek için OK tuşuna basın',
    'attempt':        'Deneme',
    'streamErrorDetailed': 'Bu içerik şu an açılamıyor. Lütfen internet bağlantınızı veya sunucunuzdaki yayını kontrol edin.\n\nHata Veren Adres:',
    'sleepTimer':     'Uyku Zamanlayıcı',
    'noNetwork':      'İnternet bağlantısı kesildi. Bekleniyor...',
    'playbackError':  'Oynatma Hatası',
    'decoderSuggestion': 'Ayarlardan Yazılımsal Kod Çözücü\'yü deneyin.',
    'decoderMode':    'Kod Çözücü Modu',
    'hwDecoder':      'Donanımsal (Hardware)',
    'swDecoder':      'Yazılımsal (Software)',
    'autoDecoder':    'Otomatik',
    'settingsTitle':  'Aladin Media Player Pro',
    'about':          'Hakkında',
    'developer':      'Geliştirici: Aladin',
    'tabM3U':         'M3U URL',
    'tabXtream':      'Xtream',
    'tabLocal':       'Lokal',
    'importing':      'İçe Aktarılıyor...',
    'connecting':     'Bağlanıyor...',
    'downloadingDots':'İndiriliyor...',
    'parsing':        'Ayrıştırılıyor...',
    'selectM3UFile':  'M3U dosyası seçin...',
    'localLoaded':    '✅ Lokal playlist yüklendi!',
    'langTitle':      'Dil / Language',
    'syncingData':    'Veriler Senkronize Ediliyor...',
    'allDrives':      'Tüm Sürücüler (USB/SD)',
    'deviceFiles':    'Cihaz Dosyaları',
    'internalStorage':'Dahili Hafıza',
    'upFolder':       '.. (Üst Klasör)',
    'accessError':    'Erişim Hatası',
    'goInternal':     'Dahili Hafızaya Git',
    'setupWizard':    'Kurulum Sihirbazı',
    'setupWizardSub': 'Hızlı ve kolay kurulum adımları',
    'addM3uTitle':    'M3U Playlist Ekle',
    'addXtreamTitle': 'Xtream Codes Girişi',
    'appAndListMgmt': 'Uygulama ve Liste Yönetimi',
    'newPlaylistAdd': 'YENİ LİSTE EKLE',
    'actions':        'İŞLEMLER',
    'version':        'Versiyon',
    'checkUpdates':   'GÜNCELLEMELERİ KONTROL ET',
    'checkingUpdates':'Güncellemeler kontrol ediliyor...',
    'upToDate':       'Uygulamanız güncel.',
    'active':         'AKTİF',
    'selectSource':   'Playlist Kaynağını Seçin',
    'm3uSub':         'Web adresi üzerinden yükle',
    'xtreamSub':      'Kullanıcı ve şifre ile giriş',
    'localSub':       'Cihazdaki .m3u dosyasını seç',
    'altProtocolTry': 'Alternatif protokol deneniyor...',
    'httpsError':     'HTTPS Hatası! Lütfen http:// ile deneyin.',
    'listSavedCount': '{count} Liste Kayıtlı',
    'm3uUrl':         'M3U URL',
    'playStore':      'Google Play Store',
    'github':         'GitHub',
    'playlistStats':  'TV: {tv} | Film: {movie} | Dizi: {series}',
    'rating':         'Puan',
    'year':           'Yıl',
    'alpha':          'A-Z',
    'noContentFound': 'Bu kategoride içerik bulunamadı.',
    'forSmartTv':     'FOR SMART TV',
    'removeFavoriteQ': '"{name}" favorilerden çıkarılsın mı?',
    'removeListQ':     '"{name}" listeden kaldırılsın mı?',
  };

  static const Map<String, String> _enMap = {
    'appNameShort':   'Aladin Player',
    'navHome':        'Home',
    'navLiveTV':      'Live TV',
    'navMovies':      'Movies',
    'navSeries':      'Series',
    'navFavorites':   'Favorites',
    'navSearch':      'Search',
    'navSettings':    'Settings',
    'retry':          'Retry',
    'cancel':         'Cancel',
    'save':           'Save',
    'delete':         'Delete',
    'update':         'Update',
    'load':           'Load',
    'connect':        'Connect',
    'close':          'Close',
    'back':           'Back',
    'results':        'results',
    'noResultsFound': 'No results found',
    'loading':        'Loading...',
    'nowLive':        'LIVE',
    'noPlaylistSelected': 'No Playlist Selected',
    'addPlaylistHint':    'Add an M3U playlist in Settings',
    'goToSettings':       'Go to Settings',
    'addPlaylist':        '+ Add Playlist',
    'noPlaylistYet':      'No playlist added yet',
    'savedPlaylists':     'Saved Playlists',
    'noPlaylistsAdded':   'No playlists added yet.',
    'demoDownloadHint':   'Demo — tap to download',
    'playlistLoaded':     '✅ Playlist loaded!',
    'playlistExists':     'Existing Playlist',
    'playlistExistsQ':    'already exists. Update it?',
    'playlistDeleted':    'Deleted',
    'playlistDeleteQ':    'delete?',
    'playlistRename':     'Rename',
    'playlistSelected':   'selected',
    'enterM3uUrl':        'Please enter an M3U URL',
    'playlistName':       'Playlist Name',
    'server':             'Server',
    'username':           'Username',
    'password':           'Password',
    'channelsSaved':      'channels saved',
    'done':               'Done',
    'error':              'Error',
    'channels':           'channels',
    'fillAllFields':      'Fill in all fields',
    'validating':         'Validating...',
    'loaded':             'loaded',
    'selectAFile':        'Select a file',
    'reading':            'Reading...',
    'local':              'Local',
    'newName':            'New name',
    'updating':           'updating',
    'updated':            'updated',
    'import':             'Import',
    'channelsShort':      'ch',
    'demoDownloadPrompt': 'Demo playlist not downloaded yet. Download now?',
    'download':           'Download',
    'continueWatching':   'Continue Watching',
    'recentlyAdded':      'Recently Added',
    'discover':           'Discover Something New',
    'noMoviesFound':  'No movies found',
    'noSeriesFound':  'No series found',
    'continueWatch':  '🕒 Continue Watching',
    'favorites':      '⭐ Favorites',
    'noFavorites':    'No favorites added yet',
    'searchHint':     'Search channels, movies, series...',
    'typeToSearch':   'Start typing to search',
    'liveTv':         'Live TV',
    'movies':         'Movies',
    'series':         'Series',
    'episodes':       'Episodes',
    'similarContent': 'Similar Content',
    'exitConfirmTitle': 'Exit Confirmation',
    'exitConfirmMsg':   'Are you sure you want to exit the app?',
    'yes':               'Yes',
    'no':                'No',
    'errorUrlTitle':    'Connection Error',
    'errorUrlMsg':      'Failed to load playlist. Please check the URL. \n\nHint: You might have used "https://" instead of "http://" or the URL might be incomplete.',
    'playlistLoadedTitle': 'Import Successful',
    'playlistLoadedMsg':   'Playlist loaded successfully. Would you like to activate it and go to the channel list now?',
    'activateNow':      'Activate Now',
    'epgNoData':      'No EPG data found',
    'epgAddSource':   'Update EPG from Settings',
    'epgNeverSynced': 'EPG never synced',
    'epgLastSync':    'EPG last updated: {days} days ago',
    'epgSyncing':     'Updating...',
    'epgUpdate':      'Update EPG',
    'epgUpdated':     '✅ EPG updated',
    'epgFirstSyncPrompt': 'Would you like to update EPG data now?',
    'epgUpdateRecommended': 'Update recommended',
    'remMinutes':     '{minutes} min left',
    'duration':       '{minutes} min',
    'ending':         'ending...',
    'channel':        'Channel',
    'audioTrack':     'Audio Track',
    'subtitles':      'Subtitles',
    'subtitlesOff':   'Off',
    'streamError':    'Stream Unavailable',
    'streamErrorMsg': 'This stream is currently unavailable. Try a different source or come back later.',
    'channelInfo':    'Channel Info',
    'movieInfo':      'Movie / Series Info',
    'epgTab':         'Programme Guide',
    'infoTab':        'Info',
    'noMovieInfo':    'No movie info found',
    'added':          'added',
    'removed':        'removed',
    'category':       'Category',
    'type':           'Type',
    'quality':        'Quality',
    'country':        'Country',
    'season':         'Season',
    'episode':        'Episode',
    'audio':          'Audio',
    'all':            'All',
    'aspectFit':      'Fit',
    'aspect169':      '16:9',
    'aspect43':       '4:3',
    'aspectFill':     'Fill',
    'aspectZoom':     'Zoom',
    'addedToFav':     'Added to favorites',
    'removedFromFav': 'Removed from favorites',
    'screenRatio':    'Screen Ratio',
    'off':            'Off',
    'favoritesShort': 'Favorite',
    'guideChannel':   '↕ Change Channel',
    'guideSeek':      '↔ Seek Forward/Back',
    'guideVolume':    '↔ Adjust Volume',
    'checkingConnection': 'Checking connection/server...',
    'retryWithOk':    'Press OK to retry',
    'attempt':        'Attempt',
    'streamErrorDetailed': 'This stream cannot be opened at the moment. Please check your internet settings or the source link on your server.\n\nFailing URL:',
    'sleepTimer':     'Sleep Timer',
    'noNetwork':      'No network connection. Waiting...',
    'playbackError':  'Playback Error',
    'decoderSuggestion': 'Try Software Decoder from settings.',
    'decoderMode':    'Decoder Mode',
    'hwDecoder':      'Hardware',
    'swDecoder':      'Software',
    'autoDecoder':    'Auto',
    'settingsTitle':  'Aladin Media Player Pro TV',
    'about':          'About',
    'developer':      'Developer: Aladin',
    'tabM3U':         'M3U URL',
    'tabXtream':      'Xtream',
    'tabLocal':       'Local',
    'importing':      'Importing...',
    'connecting':     'Connecting...',
    'downloadingDots':'Downloading...',
    'parsing':        'Parsing...',
    'selectM3UFile':  'Select M3U file...',
    'localLoaded':    '✅ Local playlist loaded!',
    'langTitle':      'Language / Dil',
    'syncingData':    'Synchronizing Data...',
    'allDrives':      'All Drives (USB/SD)',
    'deviceFiles':    'Device Files',
    'internalStorage':'Internal Storage',
    'upFolder':       '.. (Up Folder)',
    'accessError':    'Access Error',
    'goInternal':     'Go to Internal Storage',
    'setupWizard':    'Setup Wizard',
    'setupWizardSub': 'Quick and easy setup steps',
    'addM3uTitle':    'Add M3U Playlist',
    'addXtreamTitle': 'Xtream Codes Login',
    'appAndListMgmt': 'App & Playlist Management',
    'newPlaylistAdd': 'ADD NEW PLAYLIST',
    'actions':        'ACTIONS',
    'version':        'Version',
    'checkUpdates':   'CHECK FOR UPDATES',
    'checkingUpdates':'Checking for updates...',
    'upToDate':       'Your app is up to date.',
    'active':         'ACTIVE',
    'selectSource':   'Select Playlist Source',
    'm3uSub':         'Upload via web address',
    'xtreamSub':      'Login with user and password',
    'localSub':       'Select .m3u file on device',
    'altProtocolTry': 'Trying alternative protocol...',
    'httpsError':     'HTTPS Error! Please try with http://.',
    'listSavedCount': '{count} Lists Saved',
    'm3uUrl':         'M3U URL',
    'playStore':      'Google Play Store',
    'github':         'GitHub',
    'playlistStats':  'TV: {tv} | Movies: {movie} | Series: {series}',
    'rating':         'Rating',
    'year':           'Year',
    'alpha':          'A-Z',
    'noContentFound': 'No content found in this category.',
    'forSmartTv':     'FOR SMART TV',
    'removeFavoriteQ': 'Remove "{name}" from favorites?',
    'removeListQ':     'Remove "{name}" from list?',
  };

  static const Map<String, String> _deMap = {
    'appNameShort':   'Aladin Player',
    'navLiveTV':      'Live TV',
    'navMovies':      'Filme',
    'navSeries':      'Serien',
    'navFavorites':   'Favoriten',
    'navSearch':      'Suche',
    'navSettings':    'Einstellungen',
    'retry':          'Wiederholen',
    'cancel':         'Abbrechen',
    'save':           'Speichern',
    'delete':         'Löschen',
    'update':         'Aktualisieren',
    'load':           'Laden',
    'connect':        'Verbinden',
    'close':          'Schließen',
    'back':           'Zurück',
    'results':        'Ergebnisse',
    'noResultsFound': 'Keine Ergebnisse gefunden',
    'loading':        'Laden...',
    'nowLive':        'LIVE',
    'noPlaylistSelected': 'Keine Playlist ausgewählt',
    'addPlaylistHint':    'M3U-Playlist in den Einstellungen hinzufügen',
    'goToSettings':       'Zu den Einstellungen',
    'addPlaylist':        '+ Playlist hinzufügen',
    'noPlaylistYet':      'Noch keine Playlist hinzugefügt',
    'savedPlaylists':     'Gespeicherte Playlists',
    'noPlaylistsAdded':   'Noch keine Playlists hinzugefügt.',
    'demoDownloadHint':   'Demo — zum Herunterladen tippen',
    'playlistLoaded':     '✅ Playlist geladen!',
    'playlistExists':     'Vorhandene Playlist',
    'playlistExistsQ':    'existiert bereits. Aktualisieren?',
    'playlistDeleted':    'Gelöscht',
    'playlistDeleteQ':    'löschen?',
    'playlistRename':     'Umbenennen',
    'playlistSelected':   'ausgewählt',
    'enterM3uUrl':        'Bitte M3U URL eingeben',
    'playlistName':       'Playlist-Name',
    'server':             'Server',
    'username':           'Benutzername',
    'password':           'Passwort',
    'channelsSaved':      'Kanäle gespeichert',
    'done':               'Fertig',
    'error':              'Fehler',
    'channels':           'Kanäle',
    'fillAllFields':      'Alle Felder ausfüllen',
    'validating':         'Validierung...',
    'loaded':             'geladen',
    'selectAFile':        'Datei auswählen',
    'reading':            'Lesen...',
    'local':              'Lokal',
    'newName':            'Neuer Name',
    'updating':           'aktualisierung',
    'updated':            'aktualisiert',
    'import':             'Importieren',
    'channelsShort':      'Kan.',
    'demoDownloadPrompt': 'Demo-Playlist noch nicht heruntergeladen. Jetzt herunterladen?',
    'download':           'Herunterladen',
    'continueWatching':   'Weitersehen',
    'noMoviesFound':  'Keine Filme gefunden',
    'noSeriesFound':  'Keine Serien gefunden',
    'continueWatch':  '🕒 Weitersehen',
    'favorites':      '⭐ Favoriten',
    'noFavorites':    'Noch keine Favoriten hinzugefügt',
    'searchHint':     'Kanäle, Filme, Serien suchen...',
    'typeToSearch':   'Tippen, um zu suchen',
    'liveTv':         'Live TV',
    'movies':         'Filme',
    'series':         'Serien',
    'episodes':       'Episoden',
    'similarContent': 'Ähnliche Inhalte',
    'exitConfirmTitle': 'Beenden bestätigen',
    'exitConfirmMsg':   'Möchten Sie die App wirklich beenden?',
    'yes':               'Ja',
    'no':                'Nein',
    'errorUrlTitle':    'Verbindungsfehler',
    'errorUrlMsg':      'Playlist konnte nicht geladen werden. Bitte überprüfen Sie die URL.',
    'playlistLoadedTitle': 'Import erfolgreich',
    'playlistLoadedMsg':   'Playlist erfolgreich geladen. Möchten Sie sie jetzt aktivieren?',
    'activateNow':      'Jetzt aktivieren',
    'epgNoData':      'Keine EPG-Daten gefunden',
    'epgAddSource':   'EPG in Einstellungen aktualisieren',
    'epgNeverSynced': 'EPG nie synchronisiert',
    'epgLastSync':    'EPG zuletzt aktualisiert: vor {days} Tagen',
    'epgSyncing':     'Aktualisierung...',
    'epgUpdate':      'EPG aktualisieren',
    'epgUpdated':     '✅ EPG aktualisiert',
    'remMinutes':     'Noch {minutes} Min.',
    'duration':       '{minutes} Min.',
    'ending':         'endet...',
    'channel':        'Kanal',
    'audioTrack':     'Tonspur',
    'subtitles':      'Untertitel',
    'subtitlesOff':   'Aus',
    'streamError':    'Stream nicht verfügbar',
    'channelInfo':    'Kanalinfo',
    'movieInfo':      'Film- / Serieninfo',
    'epgTab':         'Programmzeitschrift',
    'infoTab':        'Info',
    'noMovieInfo':    'Keine Filminfos gefunden',
    'added':          'hinzugefügt',
    'removed':        'entfernt',
    'category':       'Kategorie',
    'type':           'Typ',
    'quality':        'Qualität',
    'country':        'Land',
    'season':         'Staffel',
    'episode':        'Episode',
    'audio':          'Ton',
    'all':            'Alle',
    'aspectFit':      'Einpassen',
    'aspect169':      '16:9',
    'aspect43':       '4:3',
    'aspectFill':     'Füllen',
    'aspectZoom':     'Zoom',
    'addedToFav':     'Zu Favoriten hinzugefügt',
    'removedFromFav': 'Aus Favoriten entfernt',
    'screenRatio':    'Bildformat',
    'off':            'Aus',
    'favoritesShort': 'Favorit',
    'guideChannel':   '↕ Kanal wechseln',
    'guideSeek':      '↔ Vor/Zurück spulen',
    'guideVolume':    '↔ Lautstärke anpassen',
    'checkingConnection': 'Verbindung/Server wird geprüft...',
    'retryWithOk':    'Drücken Sie OK, um es erneut zu versuchen',
    'attempt':        'Versuch',
    'streamErrorDetailed': 'Dieser Stream kann momentan nicht geöffnet werden. Bitte überprüfen Sie Ihre Internetverbindung oder den Quelllink auf Ihrem Server.\n\nFehlerhafte URL:',
    'noNetwork':      'Keine Netzwerkverbindung. Warten...',
    'playbackError':  'Wiedergabefehler',
    'decoderSuggestion': 'Versuchen Sie den Software-Decoder in den Einstellungen.',
    'decoderMode':    'Decoder-Modus',
    'hwDecoder':      'Hardware',
    'swDecoder':      'Software',
    'autoDecoder':    'Auto',
    'settingsTitle':  'Aladin Media Player Pro TV',
    'tabM3U':         'M3U URL',
    'tabXtream':      'Xtream',
    'tabLocal':       'Lokal',
    'importing':      'Importieren...',
    'connecting':     'Verbinden...',
    'downloadingDots':'Laden...',
    'parsing':        'Analysieren...',
    'selectM3UFile':  'M3U-Datei auswählen...',
    'localLoaded':    '✅ Lokale Playlist geladen!',
    'langTitle':      'Sprache / Language',
    'syncingData':    'Daten werden synchronisiert...',
    'allDrives':      'Alle Laufwerke (USB/SD)',
    'deviceFiles':    'Gerätedateien',
    'internalStorage':'Interner Speicher',
    'upFolder':       '.. (Oberer Ordner)',
    'accessError':    'Zugriffsfehler',
    'goInternal':     'Zum internen Speicher',
    'setupWizard':    'Setup-Assistent',
    'setupWizardSub': 'Schnelle und einfache Einrichtungsschritte',
    'addM3uTitle':    'M3U-Playlist hinzufügen',
    'addXtreamTitle': 'Xtream Codes Login',
    'appAndListMgmt': 'App- & Playlist-Verwaltung',
    'newPlaylistAdd': 'NEUE PLAYLIST HINZUFÜGEN',
    'actions':        'AKTIONEN',
    'version':        'Version',
    'checkUpdates':   'AUF UPDATES PRÜFEN',
    'checkingUpdates':'Suche nach Updates...',
    'upToDate':       'Ihre App ist auf dem neuesten Stand.',
    'active':         'AKTIV',
    'selectSource':   'Playlist-Quelle auswählen',
    'm3uSub':         'Über Webadresse hochladen',
    'xtreamSub':      'Login mit Benutzer und Passwort',
    'localSub':       '.m3u-Datei auf dem Gerät auswählen',
    'altProtocolTry': 'Versuche alternatives Protokoll...',
    'httpsError':     'HTTPS-Fehler! Bitte versuchen Sie es mit http://.',
    'listSavedCount': '{count} Listen gespeichert',
    'm3uUrl':         'M3U-URL',
    'playStore':      'Google Play Store',
    'github':         'GitHub',
    'playlistStats':  'TV: {tv} | Filme: {movie} | Serien: {series}',
    'rating':         'Bewertung',
    'year':           'Jahr',
    'alpha':          'A-Z',
    'noContentFound': 'Kein Inhalt in dieser Kategorie gefunden.',
    'forSmartTv':     'FÜR SMART TV',
    'removeFavoriteQ': '"{name}" aus Favoriten entfernen?',
    'removeListQ':     '"{name}" aus Liste entfernen?',
    'sleepTimer':     'Sleep-Timer',
  };

  static const Map<String, String> _frMap = {
    'appNameShort':   'Aladin Player',
    'navLiveTV':      'TV en direct',
    'navMovies':      'Films',
    'navSeries':      'Séries',
    'navFavorites':   'Favoris',
    'navSearch':      'Rechercher',
    'navSettings':    'Paramètres',
    'retry':          'Réessayer',
    'cancel':         'Annuler',
    'save':           'Enregistrer',
    'delete':         'Supprimer',
    'update':         'Mettre à jour',
    'load':           'Charger',
    'connect':        'Connecter',
    'close':          'Fermer',
    'back':           'Retour',
    'results':        'résultats',
    'noResultsFound': 'Aucun résultat trouvé',
    'loading':        'Chargement...',
    'nowLive':        'EN DIRECT',
    'noPlaylistSelected': 'Aucune playlist sélectionnée',
    'addPlaylistHint':    'Ajouter une playlist M3U dans les paramètres',
    'goToSettings':       'Aller aux paramètres',
    'addPlaylist':        '+ Ajouter une playlist',
    'noPlaylistYet':      'Aucune playlist ajoutée pour le moment',
    'savedPlaylists':     'Playlists enregistrées',
    'noPlaylistsAdded':   'Aucune playlist ajoutée.',
    'demoDownloadHint':   'Démo — appuyer pour télécharger',
    'playlistLoaded':     '✅ Playlist chargée !',
    'playlistExists':     'Playlist existante',
    'playlistExistsQ':    'existe déjà. Mettre à jour ?',
    'playlistDeleted':    'Supprimée',
    'playlistDeleteQ':    'supprimer ?',
    'playlistRename':     'Renommer',
    'playlistSelected':   'sélectionnée',
    'enterM3uUrl':        'Veuillez entrer une URL M3U',
    'playlistName':       'Nom de la playlist',
    'server':             'Serveur',
    'username':           'Nom d\'utilisateur',
    'password':           'Mot de passe',
    'channelsSaved':      'chaînes enregistrées',
    'done':               'Terminé',
    'error':              'Erreur',
    'channels':           'chaînes',
    'fillAllFields':      'Remplir tous les champs',
    'validating':         'Validation...',
    'loaded':             'chargée',
    'selectAFile':        'Sélectionner un fichier',
    'reading':            'Lecture...',
    'local':              'Local',
    'newName':            'Nouveau nom',
    'updating':           'mise à jour',
    'updated':            'mise à jour',
    'import':             'Importer',
    'channelsShort':      'ch',
    'demoDownloadPrompt': 'Playlist démo non téléchargée. Télécharger maintenant ?',
    'download':           'Télécharger',
    'continueWatching':   'Continuer à regarder',
    'noMoviesFound':  'Aucun film trouvé',
    'noSeriesFound':  'Aucune série trouvée',
    'continueWatch':  '🕒 Continuer à regarder',
    'favorites':      '⭐ Favoris',
    'noFavorites':    'Aucun favori ajouté',
    'searchHint':     'Rechercher chaînes, films, séries...',
    'typeToSearch':   'Taper pour rechercher',
    'liveTv':         'TV en direct',
    'movies':         'Films',
    'series':         'Séries',
    'episodes':       'Épisodes',
    'similarContent': 'Contenu similaire',
    'exitConfirmTitle': 'Confirmation de sortie',
    'exitConfirmMsg':   'Voulez-vous vraiment quitter l\'application ?',
    'yes':               'Oui',
    'no':                'Non',
    'errorUrlTitle':    'Erreur de connexion',
    'errorUrlMsg':      'Échec du chargement de la playlist. Veuillez vérifier l\'URL.',
    'playlistLoadedTitle': 'Importation réussie',
    'playlistLoadedMsg':   'Playlist chargée avec succès. Voulez-vous l\'activer maintenant ?',
    'activateNow':      'Activer maintenant',
    'epgNoData':      'Aucune donnée EPG trouvée',
    'epgAddSource':   'Mettre à jour l\'EPG dans les paramètres',
    'epgNeverSynced': 'EPG jamais synchronisé',
    'epgLastSync':    'EPG mis à jour il y a {days} jours',
    'epgSyncing':     'Mise à jour...',
    'epgUpdate':      'Mettre à jour l\'EPG',
    'epgUpdated':     '✅ EPG mis à jour',
    'remMinutes':     '{minutes} min restantes',
    'duration':       '{minutes} min',
    'ending':         'se termine...',
    'channel':        'Chaîne',
    'audioTrack':     'Piste audio',
    'subtitles':      'Sous-titres',
    'subtitlesOff':   'Désactivé',
    'streamError':    'Flux indisponible',
    'channelInfo':    'Info chaîne',
    'movieInfo':      'Info film / série',
    'epgTab':         'Guide des programmes',
    'infoTab':        'Info',
    'noMovieInfo':    'Aucune info trouvée',
    'added':          'ajouté',
    'removed':        'supprimé',
    'category':       'Catégorie',
    'type':           'Type',
    'quality':        'Qualité',
    'country':        'Pays',
    'season':         'Saison',
    'episode':        'Épisode',
    'audio':          'Audio',
    'all':            'Tous',
    'aspectFit':      'Ajuster',
    'aspect169':      '16:9',
    'aspect43':       '4:3',
    'aspectFill':     'Remplir',
    'aspectZoom':     'Zoom',
    'addedToFav':     'Ajouté aux favoris',
    'removedFromFav': 'Retiré des favoris',
    'screenRatio':    'Ratio d\'aspect',
    'off':            'Désactivé',
    'favoritesShort': 'Favori',
    'guideChannel':   '↕ Changer de chaîne',
    'guideSeek':      '↔ Avancer/Reculer',
    'guideVolume':    '↔ Régler le volume',
    'checkingConnection': 'Vérification connexion/serveur...',
    'retryWithOk':    'Appuyez sur OK pour réessayer',
    'attempt':        'Tentative',
    'streamErrorDetailed': 'Ce flux ne peut pas être ouvert pour le moment. Veuillez vérifier vos paramètres internet ou le lien source sur votre serveur.\n\nURL en échec:',
    'noNetwork':      'Pas de connexion réseau. En attente...',
    'playbackError':  'Erreur de lecture',
    'decoderSuggestion': 'Essayez le décodeur logiciel dans les paramètres.',
    'decoderMode':    'Mode décodeur',
    'hwDecoder':      'Matériel',
    'swDecoder':      'Logiciel',
    'autoDecoder':    'Auto',
    'settingsTitle':  'Aladin Media Player Pro TV',
    'tabM3U':         'URL M3U',
    'tabXtream':      'Xtream',
    'tabLocal':       'Local',
    'importing':      'Importation...',
    'connecting':     'Connexion...',
    'downloadingDots':'Téléchargement...',
    'parsing':        'Analyse...',
    'selectM3UFile':  'Sélectionner un fichier M3U...',
    'localLoaded':    '✅ Playlist locale chargée !',
    'langTitle':      'Langue / Language',
    'syncingData':    'Synchronisation des données...',
    'allDrives':      'Toutes les unités (USB/SD)',
    'deviceFiles':    'Fichiers du périphérique',
    'internalStorage':'Mémoire interne',
    'upFolder':       '.. (Dossier parent)',
    'accessError':    'Erreur d\'accès',
    'goInternal':     'Aller à la mémoire interne',
    'setupWizard':    'Assistant de configuration',
    'setupWizardSub': 'Étapes de configuration rapides et faciles',
    'addM3uTitle':    'Ajouter une playlist M3U',
    'addXtreamTitle': 'Connexion Xtream Codes',
    'appAndListMgmt': 'Gestion des applications et des listes',
    'newPlaylistAdd': 'AJOUTER UNE NOUVELLE PLAYLIST',
    'actions':        'ACTIONS',
    'version':        'Version',
    'checkUpdates':   'VÉRIFIER LES MISES À JOUR',
    'checkingUpdates':'Vérification des mises à jour...',
    'upToDate':       'Votre application est à jour.',
    'active':         'ACTIF',
    'selectSource':   'Sélectionner la source de la playlist',
    'm3uSub':         'Télécharger via l\'adresse web',
    'xtreamSub':      'Connexion avec utilisateur et mot de passe',
    'localSub':       'Sélectionner le fichier .m3u sur l\'appareil',
    'altProtocolTry': 'Essai d\'un protocole alternatif...',
    'httpsError':     'Erreur HTTPS ! Veuillez essayer avec http://.',
    'listSavedCount': '{count} listes enregistrées',
    'm3uUrl':         'URL M3U',
    'playStore':      'Google Play Store',
    'github':         'GitHub',
    'playlistStats':  'TV : {tv} | Films : {movie} | Séries : {series}',
    'rating':         'Note',
    'year':           'Année',
    'alpha':          'A-Z',
    'noContentFound': 'Aucun contenu trouvé dans cette catégorie.',
    'forSmartTv':     'POUR SMART TV',
    'removeFavoriteQ': 'Retirer "{name}" des favoris ?',
    'removeListQ':     'Supprimer "{name}" de la liste ?',
    'sleepTimer':     'Minuterie de mise en veille',
  };

  static const Map<String, String> _esMap = {
    'appNameShort':   'Aladin Player',
    'navLiveTV':      'TV en vivo',
    'navMovies':      'Películas',
    'navSeries':      'Series',
    'navFavorites':   'Favoritos',
    'navSearch':      'Buscar',
    'navSettings':    'Ajustes',
    'retry':          'Reintentar',
    'cancel':         'Cancelar',
    'save':           'Guardar',
    'delete':         'Eliminar',
    'update':         'Actualizar',
    'load':           'Cargar',
    'connect':        'Conectar',
    'close':          'Cerrar',
    'back':           'Atrás',
    'results':        'resultados',
    'noResultsFound': 'No se encontraron resultados',
    'loading':        'Cargando...',
    'nowLive':        'EN VIVO',
    'noPlaylistSelected': 'Sin lista seleccionada',
    'addPlaylistHint':    'Añade una lista M3U en Ajustes',
    'goToSettings':       'Ir a Ajustes',
    'addPlaylist':        '+ Añadir lista',
    'noPlaylistYet':      'Aún no hay listas',
    'savedPlaylists':     'Listas guardadas',
    'noPlaylistsAdded':   'No hay listas añadidas.',
    'demoDownloadHint':   'Demo — toca para descargar',
    'playlistLoaded':     '✅ ¡Lista cargada!',
    'playlistExists':     'Lista existente',
    'playlistExistsQ':    'ya existe. ¿Actualizar?',
    'playlistDeleted':    'Eliminada',
    'playlistDeleteQ':    '¿eliminar?',
    'playlistRename':     'Renombrar',
    'playlistSelected':   'seleccionada',
    'enterM3uUrl':        'Ingrese URL M3U',
    'playlistName':       'Nombre de la lista',
    'server':             'Servidor',
    'username':           'Usuario',
    'password':           'Contraseña',
    'channelsSaved':      'canales guardados',
    'done':               'Hecho',
    'error':              'Error',
    'channels':           'canales',
    'fillAllFields':      'Complete todos los campos',
    'validating':         'Validando...',
    'loaded':             'cargada',
    'selectAFile':        'Seleccione un archivo',
    'reading':            'Leyendo...',
    'local':              'Local',
    'newName':            'Nuevo nombre',
    'updating':           'actualizando',
    'updated':            'actualizada',
    'import':             'Importar',
    'channelsShort':      'can.',
    'demoDownloadPrompt': 'Lista demo no descargada. ¿Descargar ahora?',
    'download':           'Descargar',
    'continueWatching':   'Continuar viendo',
    'noMoviesFound':  'No se encontraron películas',
    'noSeriesFound':  'No se encontraron series',
    'continueWatch':  '🕒 Continuar viendo',
    'favorites':      '⭐ Favoritos',
    'noFavorites':    'Aún no hay favoritos',
    'searchHint':     'Buscar canales, cine, series...',
    'typeToSearch':   'Escriba para buscar',
    'liveTv':         'TV en vivo',
    'movies':         'Películas',
    'series':         'Series',
    'episodes':       'Episodios',
    'similarContent': 'Contenido similar',
    'exitConfirmTitle': 'Confirmar salida',
    'exitConfirmMsg':   '¿Seguro que quieres salir?',
    'yes':               'Sí',
    'no':                'No',
    'errorUrlTitle':    'Error de conexión',
    'errorUrlMsg':      'Error al cargar la lista. Verifique la URL.',
    'playlistLoadedTitle': 'Importación exitosa',
    'playlistLoadedMsg':   'Lista cargada. ¿Activar ahora?',
    'activateNow':      'Activar ahora',
    'epgNoData':      'Sin datos EPG',
    'epgAddSource':   'Actualizar EPG en Ajustes',
    'epgNeverSynced': 'EPG nunca sincronizada',
    'epgLastSync':    'EPG actualizada hace {days} días',
    'epgSyncing':     'Actualizando...',
    'epgUpdate':      'Actualizar EPG',
    'epgUpdated':     '✅ EPG actualizada',
    'remMinutes':     'faltan {minutes} min',
    'duration':       '{minutes} min',
    'ending':         'terminando...',
    'channel':        'Canal',
    'audioTrack':     'Pista de audio',
    'subtitles':      'Subtítulos',
    'subtitlesOff':   'Desactivado',
    'streamError':    'Stream no disponible',
    'channelInfo':    'Info canal',
    'movieInfo':      'Info película / serie',
    'epgTab':         'Guía de programación',
    'infoTab':        'Info',
    'noMovieInfo':    'No hay info disponible',
    'added':          'añadido',
    'removed':        'quitado',
    'category':       'Categoría',
    'type':           'Tipo',
    'quality':        'Calidad',
    'country':        'País',
    'season':         'Temporada',
    'episode':        'Episodio',
    'audio':          'Audio',
    'all':            'Todo',
    'aspectFit':      'Ajustar',
    'aspect169':      '16:9',
    'aspect43':       '4:3',
    'aspectFill':     'Llenar',
    'aspectZoom':     'Zoom',
    'addedToFav':     'Añadido a favoritos',
    'removedFromFav': 'Quitado de favoritos',
    'screenRatio':    'Relación de aspecto',
    'off':            'Desactivado',
    'favoritesShort': 'Favorito',
    'guideChannel':   '↕ Cambiar canal',
    'guideSeek':      '↔ Adelantar/Retroceder',
    'guideVolume':    '↔ Ajustar volumen',
    'checkingConnection': 'Comprobando conexión/servidor...',
    'retryWithOk':    'Presione OK para reintentar',
    'attempt':        'Intento',
    'streamErrorDetailed': 'Este stream no se puede abrir en este momento. Por favor, compruebe su configuración de internet o el enlace de origen en su servidor.\n\nURL con error:',
    'noNetwork':      'Sin conexión de red. Esperando...',
    'playbackError':  'Error de reproducción',
    'decoderSuggestion': 'Pruebe el decodificador de software en los ajustes.',
    'decoderMode':    'Modo decodificador',
    'hwDecoder':      'Hardware',
    'swDecoder':      'Software',
    'autoDecoder':    'Auto',
    'settingsTitle':  'Aladin Media Player Pro TV',
    'tabM3U':         'URL M3U',
    'tabXtream':      'Xtream',
    'tabLocal':       'Local',
    'importing':      'Importando...',
    'connecting':     'Conectando...',
    'downloadingDots':'Descargando...',
    'parsing':        'Analizando...',
    'selectM3UFile':  'Seleccionar archivo M3U...',
    'localLoaded':    '✅ ¡Lista local cargada!',
    'langTitle':      'Idioma / Language',
    'syncingData':    'Sincronizando datos...',
    'allDrives':      'Todas las unidades (USB/SD)',
    'deviceFiles':    'Archivos del dispositivo',
    'internalStorage':'Almacenamiento interno',
    'upFolder':       '.. (Carpeta superior)',
    'accessError':    'Error de acceso',
    'goInternal':     'Ir al almacenamiento interno',
    'setupWizard':    'Asistente de configuración',
    'setupWizardSub': 'Pasos de configuración rápidos y sencillos',
    'addM3uTitle':    'Añadir lista de reproducción M3U',
    'addXtreamTitle': 'Inicio de sesión de Xtream Codes',
    'appAndListMgmt': 'Gestión de aplicaciones y listas',
    'newPlaylistAdd': 'AÑADIR NUEVA LISTA DE REPRODUCCIÓN',
    'actions':        'ACCIONES',
    'version':        'Versión',
    'checkUpdates':   'BUSCAR ACTUALIZACIONES',
    'checkingUpdates':'Buscando actualizaciones...',
    'upToDate':       'Su aplicación está actualizada.',
    'active':         'ACTIVO',
    'selectSource':   'Seleccionar fuente de lista de reproducción',
    'm3uSub':         'Cargar a través de la dirección web',
    'xtreamSub':      'Iniciar sesión con usuario y contraseña',
    'localSub':       'Seleccionar archivo .m3u en el dispositivo',
    'altProtocolTry': 'Probando protocolo alternativo...',
    'httpsError':     '¡Error de HTTPS! Inténtalo con http://.',
    'listSavedCount': '{count} listas guardadas',
    'm3uUrl':         'URL M3U',
    'playStore':      'Google Play Store',
    'github':         'GitHub',
    'playlistStats':  'TV: {tv} | Cine: {movie} | Series: {series}',
    'rating':         'Calificación',
    'year':           'Año',
    'alpha':          'A-Z',
    'noContentFound': 'No se encontró contenido en esta categoría.',
    'forSmartTv':     'PARA SMART TV',
    'removeFavoriteQ': '¿Quitar "{name}" de favoritos?',
    'removeListQ':     '¿Eliminar "{name}" de la lista?',
    'sleepTimer':     'Temporizador de apagado',
  };

  static const Map<String, String> _ruMap = {
    'appNameShort':   'Aladin Player',
    'navLiveTV':      'Прямой эфир',
    'navMovies':      'Фильмы',
    'navSeries':      'Сериалы',
    'navFavorites':   'Избранное',
    'navSearch':      'Поиск',
    'navSettings':    'Настройки',
    'retry':          'Повторить',
    'cancel':         'Отмена',
    'save':           'Сохранить',
    'delete':         'Удалить',
    'update':         'Обновить',
    'load':           'Загрузить',
    'connect':        'Подключиться',
    'close':          'Закрыть',
    'back':           'Назад',
    'results':        'результатов',
    'noResultsFound': 'Результатов не найдено',
    'loading':        'Загрузка...',
    'nowLive':        'В ЭФИРЕ',
    'noPlaylistSelected': 'Плейлист не выбран',
    'addPlaylistHint':    'Добавьте плейлист M3U в Настройках',
    'goToSettings':       'Перейти в Настройки',
    'addPlaylist':        '+ Добавить плейлист',
    'noPlaylistYet':      'Плейлисты не добавлены',
    'savedPlaylists':     'Сохраненные плейлисты',
    'noPlaylistsAdded':   'Нет добавленных плейлистов.',
    'demoDownloadHint':   'Демо — нажмите для загрузки',
    'playlistLoaded':     '✅ Плейлист загружен!',
    'playlistExists':     'Плейлист уже существует',
    'playlistExistsQ':    'уже есть. Обновить?',
    'playlistDeleted':    'Удалено',
    'playlistDeleteQ':    'удалить?',
    'playlistRename':     'Переименовать',
    'playlistSelected':   'выбран',
    'enterM3uUrl':        'Введите URL M3U',
    'playlistName':       'Имя плейлиста',
    'server':             'Сервер',
    'username':           'Логин',
    'password':           'Пароль',
    'channelsSaved':      'каналов сохранено',
    'done':               'Готово',
    'error':              'Ошибка',
    'channels':           'каналов',
    'fillAllFields':      'Заполните все поля',
    'validating':         'Проверка...',
    'loaded':             'загружен',
    'selectAFile':        'Выберите файл',
    'reading':            'Чтение...',
    'local':              'Локальный',
    'newName':            'Новое имя',
    'updating':           'обновление',
    'updated':            'обновлено',
    'import':             'Импорт',
    'channelsShort':      'кан.',
    'demoDownloadPrompt': 'Демо-плейлист не загружен. Скачать сейчас?',
    'download':           'Скачать',
    'continueWatching':   'Продолжить просмотр',
    'noMoviesFound':  'Фильмы не найдены',
    'noSeriesFound':  'Сериалы не найдены',
    'continueWatch':  '🕒 Продолжить',
    'favorites':      '⭐ Избранное',
    'noFavorites':    'В избранном пока пусто',
    'searchHint':     'Поиск каналов, фильмов...',
    'typeToSearch':   'Начните вводить для поиска',
    'liveTv':         'ТВ',
    'movies':         'Фильмы',
    'series':         'Сериалы',
    'episodes':       'Серии',
    'similarContent': 'Похожее',
    'exitConfirmTitle': 'Выход',
    'exitConfirmMsg':   'Вы действительно хотите выйти?',
    'yes':               'Да',
    'no':                'Нет',
    'errorUrlTitle':    'Ошибка подключения',
    'errorUrlMsg':      'Не удалось загрузить плейлист. Проверьте URL.',
    'playlistLoadedTitle': 'Импорт завершен',
    'playlistLoadedMsg':   'Плейлист загружен. Активировать сейчас?',
    'activateNow':      'Активировать',
    'epgNoData':      'Нет данных EPG',
    'epgAddSource':   'Обновите EPG в Настройках',
    'epgNeverSynced': 'EPG не обновлялась',
    'epgLastSync':    'Обновлено {days} дн. назад',
    'epgSyncing':     'Обновление...',
    'epgUpdate':      'Обновить EPG',
    'epgUpdated':     '✅ EPG обновлена',
    'remMinutes':     'осталось {minutes} мин',
    'duration':       '{minutes} мин',
    'ending':         'завершается...',
    'channel':        'Канал',
    'audioTrack':     'Аудиодорожка',
    'subtitles':      'Субтитры',
    'subtitlesOff':   'Выкл',
    'streamError':    'Поток недоступен',
    'channelInfo':    'Инфо о канале',
    'movieInfo':      'Инфо о фильме/сериале',
    'epgTab':         'Программа передач',
    'infoTab':        'Инфо',
    'noMovieInfo':    'Инфо не найдена',
    'added':          'добавлено',
    'removed':        'удалено',
    'category':       'Категория',
    'type':           'Тип',
    'quality':        'Качество',
    'country':        'Страна',
    'season':         'Сезон',
    'episode':        'Серия',
    'audio':          'Звук',
    'all':            'Все',
    'aspectFit':      'Вписать',
    'aspect169':      '16:9',
    'aspect43':       '4:3',
    'aspectFill':     'Заполнить',
    'aspectZoom':     'Zoom',
    'addedToFav':     'Добавлено в избранное',
    'removedFromFav': 'Удалено из избранного',
    'screenRatio':    'Соотношение сторон',
    'off':            'Выкл',
    'favoritesShort': 'Избранное',
    'guideChannel':   '↕ Сменить канал',
    'guideSeek':      '↔ Вперед/Назад',
    'guideVolume':    '↔ Громкость',
    'checkingConnection': 'Проверка соединения/сервера...',
    'retryWithOk':    'Нажмите OK, чтобы повторить попытку',
    'attempt':        'Попытка',
    'streamErrorDetailed': 'Этот поток не может быть открыт в данный момент. Пожалуйста, проверьте настройки интернета или исходную ссылку на вашем сервере.\n\nОшибка URL:',
    'noNetwork':      'Нет сетевого подключения. Ожидание...',
    'playbackError':  'Ошибка воспроизведения',
    'decoderSuggestion': 'Попробуйте программный декодер в настройках.',
    'decoderMode':    'Режим декодера',
    'hwDecoder':      'Аппаратный',
    'swDecoder':      'Программный',
    'autoDecoder':    'Авто',
    'settingsTitle':  'Aladin Media Player Pro TV',
    'tabM3U':         'M3U URL',
    'tabXtream':      'Xtream',
    'tabLocal':       'Локально',
    'importing':      'Импорт...',
    'connecting':     'Подключение...',
    'downloadingDots':'Загрузка...',
    'parsing':        'Анализ...',
    'selectM3UFile':  'Выберите файл M3U...',
    'localLoaded':    '✅ Файл загружен!',
    'langTitle':      'Язык / Language',
    'syncingData':    'Синхронизация...',
    'allDrives':      'Все диски (USB/SD)',
    'deviceFiles':    'Файлы устройства',
    'internalStorage':'Внутренняя память',
    'upFolder':       '.. (Вверх)',
    'accessError':    'Ошибка доступа',
    'goInternal':     'В память устройства',
    'setupWizard':    'Мастер настройки',
    'setupWizardSub': 'Быстрая и простая настройка',
    'addM3uTitle':    'Добавить плейлист M3U',
    'addXtreamTitle': 'Вход Xtream Codes',
    'appAndListMgmt': 'Управление приложением и плейлистами',
    'newPlaylistAdd': 'ДОБАВИТЬ НОВЫЙ ПЛЕЙЛИСТ',
    'actions':        'ДЕЙСТВИЯ',
    'version':        'Версия',
    'checkUpdates':   'ПРОВЕРИТЬ ОБНОВЛЕНИЯ',
    'checkingUpdates':'Проверка обновлений...',
    'upToDate':       'Приложение обновлено.',
    'active':         'АКТИВЕН',
    'selectSource':   'Выберите источник плейлиста',
    'm3uSub':         'Загрузить по веб-адресу',
    'xtreamSub':      'Вход по логину и паролю',
    'localSub':       'Выбрать файл .m3u на устройстве',
    'altProtocolTry': 'Попытка альтернативного протокола...',
    'httpsError':     'Ошибка HTTPS! Попробуйте с http://.',
    'listSavedCount': 'Сохранено списков: {count}',
    'm3uUrl':         'M3U URL',
    'playStore':      'Google Play Store',
    'github':         'GitHub',
    'playlistStats':  'ТВ: {tv} | Фильмы: {movie} | Сериалы: {series}',
    'rating':         'Рейтинг',
    'year':           'Год',
    'alpha':          'А-Я',
    'noContentFound': 'В этой категории ничего не найдено.',
    'forSmartTv':     'ДЛЯ SMART TV',
    'removeFavoriteQ': 'Удалить "{name}" из избранного?',
    'removeListQ':     'Удалить "{name}" из списка?',
    'sleepTimer':     'Таймер сна',
  };

  static const Map<String, String> _zhMap = {
    'appNameShort':   'Aladin Player',
    'navLiveTV':      '直播电视',
    'navMovies':      '电影',
    'navSeries':      '剧集',
    'navFavorites':   '收藏',
    'navSearch':      '搜索',
    'navSettings':    '设置',
    'retry':          '重试',
    'cancel':         '取消',
    'save':           '保存',
    'delete':         '删除',
    'update':         '更新',
    'load':           '加载',
    'connect':        '连接',
    'close':          '关闭',
    'back':           '返回',
    'results':        '结果',
    'noResultsFound': '未找到结果',
    'loading':        '加载中...',
    'nowLive':        '直播中',
    'noPlaylistSelected': '未选择播放列表',
    'addPlaylistHint':    '在设置中添加M3U播放列表',
    'goToSettings':       '前往设置',
    'addPlaylist':        '+ 添加播放列表',
    'noPlaylistYet':      '尚未添加播放列表',
    'savedPlaylists':     '已存播放列表',
    'noPlaylistsAdded':   '没有已添加的播放列表。',
    'demoDownloadHint':   '演示 — 点击下载',
    'playlistLoaded':     '✅ 播放列表已加载！',
    'playlistExists':     '已存在播放列表',
    'playlistExistsQ':    '已经存在。是否更新？',
    'playlistDeleted':    '已删除',
    'playlistDeleteQ':    '确认删除？',
    'playlistRename':     '重命名',
    'playlistSelected':   '已选择',
    'enterM3uUrl':        '请输入M3U URL',
    'playlistName':       '播放列表名称',
    'server':             '服务器',
    'username':           '用户名',
    'password':           '密码',
    'channelsSaved':      '个频道已保存',
    'done':               '完成',
    'error':              '错误',
    'channels':           '个频道',
    'fillAllFields':      '请填写所有字段',
    'validating':         '验证中...',
    'loaded':             '已加载',
    'selectAFile':        '选择文件',
    'reading':            '读取中...',
    'local':              '本地',
    'newName':            '新名称',
    'updating':           '更新中',
    'updated':            '已更新',
    'import':             '导入',
    'channelsShort':      '频道',
    'demoDownloadPrompt': '演示播放列表尚未下载。现在下载？',
    'download':           '下载',
    'continueWatching':   '继续观看',
    'noMoviesFound':  '未找到电影',
    'noSeriesFound':  '未找到剧集',
    'continueWatch':  '🕒 继续观看',
    'favorites':      '⭐ 我的收藏',
    'noFavorites':    '尚未添加收藏',
    'searchHint':     '搜索频道、电影、剧集...',
    'typeToSearch':   '开始输入搜索',
    'liveTv':         '直播电视',
    'movies':         '电影',
    'series':         '剧集',
    'episodes':       '分集',
    'similarContent': '相似内容',
    'exitConfirmTitle': '退出确认',
    'exitConfirmMsg':   '确定要退出应用吗？',
    'yes':               '是',
    'no':                '否',
    'errorUrlTitle':    '连接错误',
    'errorUrlMsg':      '加载播放列表失败。请检查 URL。',
    'playlistLoadedTitle': '导入成功',
    'playlistLoadedMsg':   '播放列表已加载。立即激活？',
    'activateNow':      '立即激活',
    'epgNoData':      '无节目表数据',
    'epgAddSource':   '在设置中更新节目表',
    'epgNeverSynced': '节目表未同步',
    'epgLastSync':    '{days} 天前同步过',
    'epgSyncing':     '同步中...',
    'epgUpdate':      '更新节目表',
    'epgUpdated':     '✅ 节目表已更新',
    'remMinutes':     '剩余 {minutes} 分钟',
    'duration':       '{minutes} 分钟',
    'ending':         '即将结束...',
    'channel':        '频道',
    'audioTrack':     '音频轨道',
    'subtitles':      '字幕',
    'subtitlesOff':   '关闭',
    'streamError':    '无法播放流',
    'channelInfo':    '频道信息',
    'movieInfo':      '影视信息',
    'epgTab':         '节目指南',
    'infoTab':        '信息',
    'noMovieInfo':    '未找到信息',
    'added':          '已添加',
    'removed':        '已移除',
    'category':       '类别',
    'type':           '类型',
    'quality':        '画质',
    'country':        '国家',
    'season':         '季',
    'episode':        '集',
    'audio':          '音频',
    'all':            '全部',
    'aspectFit':      '自适应',
    'aspect169':      '16:9',
    'aspect43':       '4:3',
    'aspectFill':     '填充',
    'aspectZoom':     '缩放',
    'addedToFav':     '已添加到收藏夹',
    'removedFromFav': '已从收藏夹中移除',
    'screenRatio':    '屏幕比例',
    'off':            '关闭',
    'favoritesShort': '收藏',
    'guideChannel':   '↕ 切换频道',
    'guideSeek':      '↔ 快进/快退',
    'guideVolume':    '↔ 调节音量',
    'checkingConnection': '正在检查连接/服务器...',
    'retryWithOk':    '按确定键重试',
    'attempt':        '尝试',
    'streamErrorDetailed': '目前无法打开此流。请检查您的网络设置或服务器上的源链接。\n\n错误的 URL:',
    'noNetwork':      '无网络连接。正在等待...',
    'playbackError':  '播放错误',
    'decoderSuggestion': '请在设置中尝试软件解码器。',
    'decoderMode':    '解码器模式',
    'hwDecoder':      '硬件解码',
    'swDecoder':      '软件解码',
    'autoDecoder':    '自动',
    'settingsTitle':  'Aladin Media Player Pro TV',
    'tabM3U':         'M3U URL',
    'tabXtream':      'Xtream',
    'tabLocal':       '本地文件',
    'importing':      '导入中...',
    'connecting':     '连接中...',
    'downloadingDots':'下载中...',
    'parsing':        '解析中...',
    'selectM3UFile':  '选择 M3U 文件...',
    'localLoaded':    '✅ 本地播放列表已加载！',
    'langTitle':      '语言 / Language',
    'syncingData':    '数据同步中...',
    'allDrives':      '所有驱动器 (USB/SD)',
    'deviceFiles':    '设备文件',
    'internalStorage':'内部存储',
    'upFolder':       '.. (上级文件夹)',
    'accessError':    '访问错误',
    'goInternal':     '前往内部存储',
    'setupWizard':    '设置向导',
    'setupWizardSub': '快速简便的设置步骤',
    'addM3uTitle':    '添加 M3U 播放列表',
    'addXtreamTitle': 'Xtream Codes 登录',
    'appAndListMgmt': '应用与播放列表管理',
    'newPlaylistAdd': '添加新播放列表',
    'actions':        '操作',
    'version':        '版本',
    'checkUpdates':   '检查更新',
    'checkingUpdates':'正在检查更新...',
    'upToDate':       '您的应用已是最新版本。',
    'active':         '激活',
    'selectSource':   '选择播放列表来源',
    'm3uSub':         '通过网址上传',
    'xtreamSub':      '使用用户名和密码登录',
    'localSub':       '选择设备上的 .m3u 文件',
    'altProtocolTry': '尝试备用协议...',
    'httpsError':     'HTTPS 错误！请尝试使用 http://。',
    'listSavedCount': '已保存 {count} 个列表',
    'm3uUrl':         'M3U URL',
    'playStore':      'Google Play Store',
    'github':         'GitHub',
    'playlistStats':  '电视: {tv} | 电影: {movie} | 剧集: {series}',
    'rating':         '评分',
    'year':           '年份',
    'alpha':          'A-Z',
    'noContentFound': '该类别下未找到内容。',
    'forSmartTv':     '适用于智能电视',
    'removeFavoriteQ': '将 "{name}" 从收藏夹中移除？',
    'removeListQ':     '将 "{name}" 从列表中移除？',
    'sleepTimer':     '睡眠定时器',
  };

  static const Map<String, String> _arMap = {
    'appNameShort':   'Aladin Player',
    'navLiveTV':      'بث مباشر',
    'navMovies':      'أفلام',
    'navSeries':      'مسلسلات',
    'navFavorites':   'المفضلة',
    'navSearch':      'بحث',
    'navSettings':    'الإعدادات',
    'retry':          'إعادة المحاولة',
    'cancel':         'إلغاء',
    'save':           'حفظ',
    'delete':         'حذف',
    'update':         'تحديث',
    'load':           'تحميل',
    'connect':        'اتصال',
    'close':          'إغلاق',
    'back':           'رجوع',
    'results':        'نتائج',
    'noResultsFound': 'لم يتم العثور على نتائج',
    'loading':        'جاري التحميل...',
    'nowLive':        'مباشر الآن',
    'noPlaylistSelected': 'لم يتم اختيار قائمة',
    'addPlaylistHint':    'أضف قائمة M3U من الإعدادات',
    'goToSettings':       'الذهاب للإعدادات',
    'addPlaylist':        '+ إضافة قائمة',
    'noPlaylistYet':      'لم يتم إضافة قائمة بعد',
    'savedPlaylists':     'القوائم المحفوظة',
    'noPlaylistsAdded':   'لا يوجد قوائم مضافة.',
    'demoDownloadHint':   'تجريبي — اضغط للتحميل',
    'playlistLoaded':     '✅ تم تحميل القائمة!',
    'playlistExists':     'قائمة موجودة',
    'playlistExistsQ':    'موجودة بالفعل. هل تريد التحديث؟',
    'playlistDeleted':    'تم الحذف',
    'playlistDeleteQ':    'حذف؟',
    'playlistRename':     'إعادة تسمية',
    'playlistSelected':   'تم الاختيار',
    'enterM3uUrl':        'يرجى إدخال رابط M3U',
    'playlistName':       'اسم القائمة',
    'server':             'السيرفر',
    'username':           'اسم المستخدم',
    'password':           'كلمة المرور',
    'channelsSaved':      'قنوات تم حفظها',
    'done':               'تم',
    'error':              'خطأ',
    'channels':           'قنوات',
    'fillAllFields':      'يرجى ملء جميع الحقول',
    'validating':         'جاري التحقق...',
    'loaded':             'محملة',
    'selectAFile':        'اختر ملفاً',
    'reading':            'جاري القراءة...',
    'local':              'محلي',
    'newName':            'اسم جديد',
    'updating':           'جاري التحديث',
    'updated':            'تم التحديث',
    'import':             'استيراد',
    'channelsShort':      'قناة',
    'demoDownloadPrompt': 'القائمة التجريبية لم تُحمل بعد. تحميل الآن؟',
    'download':           'تحميل',
    'continueWatching':   'متابعة المشاهدة',
    'noMoviesFound':  'لم يتم العثور على أفلام',
    'noSeriesFound':  'لم يتم العثور على مسلسلات',
    'continueWatch':  '🕒 متابعة المشاهدة',
    'favorites':      '⭐ المفضلة',
    'noFavorites':    'لا يوجد مفضلات بعد',
    'searchHint':     'بحث عن قنوات، أفلام، مسلسلات...',
    'typeToSearch':   'ابدأ الكتابة للبحث',
    'liveTv':         'بث مباشر',
    'movies':         'أفلام',
    'series':         'مسلسلات',
    'episodes':       'الحلقات',
    'similarContent': 'محتوى مشابه',
    'exitConfirmTitle': 'تأكيد الخروج',
    'exitConfirmMsg':   'هل أنت متأكد من الخروج؟',
    'yes':               'نعم',
    'no':                'لا',
    'errorUrlTitle':    'خطأ في الاتصال',
    'errorUrlMsg':      'فشل تحميل القائمة. يرجى التحقق من الرابط.',
    'playlistLoadedTitle': 'نجح الاستيراد',
    'playlistLoadedMsg':   'تم تحميل القائمة بنجاح. هل تريد التفعيل الآن؟',
    'activateNow':      'تفعيل الآن',
    'epgNoData':      'لا توجد بيانات EPG',
    'epgAddSource':   'تحديث EPG من الإعدادات',
    'epgNeverSynced': 'لم يتم تحديث EPG أبداً',
    'epgLastSync':    'آخر تحديث: منذ {days} أيام',
    'epgSyncing':     'جاري التحديث...',
    'epgUpdate':      'تحديث EPG',
    'epgUpdated':     '✅ تم تحديث EPG',
    'remMinutes':     'متبقي {minutes} دقيقة',
    'duration':       '{minutes} دقيقة',
    'ending':         'ينتهي قريباً...',
    'channel':        'قناة',
    'audioTrack':     'المسار الصوتي',
    'subtitles':      'الترجمة',
    'subtitlesOff':   'إيقاف',
    'streamError':    'البث غير متاح',
    'channelInfo':    'معلومات القناة',
    'movieInfo':      'معلومات الفيلم / المسلسل',
    'epgTab':         'دليل البرامج',
    'infoTab':        'معلومات',
    'noMovieInfo':    'لا توجد معلومات',
    'added':          'تمت الإضافة',
    'removed':        'تمت الإزالة',
    'category':       'الفئة',
    'type':           'النوع',
    'quality':        'الجودة',
    'country':        'البلد',
    'season':         'الموسم',
    'episode':        'الحلقة',
    'audio':          'الصوت',
    'all':            'الكل',
    'aspectFit':      'احتواء',
    'aspect169':      '16:9',
    'aspect43':       '4:3',
    'aspectFill':     'ملء الشاشة',
    'aspectZoom':     'تكبير',
    'addedToFav':     'تمت الإضافة للمفضلة',
    'removedFromFav': 'تمت الإزالة من المفضلة',
    'screenRatio':    'نسبة الشاشة',
    'off':            'إيقاف',
    'favoritesShort': 'مفضلة',
    'guideChannel':   '↕ تغيير القناة',
    'guideSeek':      '↔ تقديم/تأخير',
    'guideVolume':    '↔ ضبط الصوت',
    'checkingConnection': 'جاري التحقق من الاتصال/السيرفر...',
    'retryWithOk':    'اضغط على موافق لإعادة المحاولة',
    'attempt':        'محاولة',
    'streamErrorDetailed': 'لا يمكن فتح هذا البث في الوقت الحالي. يرجى التحقق من إعدادات الإنترنت أو رابط المصدر على الخادم الخاص بك.\n\nالرابط المتعطل:',
    'noNetwork':      'لا يوجد اتصال بالشبكة. جاري الانتظار...',
    'playbackError':  'خطأ في التشغيل',
    'decoderSuggestion': 'جرب فك الترميز البرمجي من الإعدادات.',
    'decoderMode':    'وضع فك الترميز',
    'hwDecoder':      'عتادي (Hardware)',
    'swDecoder':      'برمجي (Software)',
    'autoDecoder':    'تلقائي',
    'settingsTitle':  'Aladin Media Player Pro TV',
    'tabM3U':         'M3U URL',
    'tabXtream':      'Xtream',
    'tabLocal':       'محلي',
    'importing':      'جاري الاستيراد...',
    'connecting':     'جاري الاتصال...',
    'downloadingDots':'جاري التحميل...',
    'parsing':        'جاري التحليل...',
    'selectM3UFile':  'اختر ملف M3U...',
    'localLoaded':    '✅ تم تحميل القائمة المحلية!',
    'langTitle':      'اللغة / Language',
    'syncingData':    'جاري مزامنة البيانات...',
    'allDrives':      'جميع الأقراص (USB/SD)',
    'deviceFiles':    'ملفات الجهاز',
    'internalStorage':'الذاكرة الداخلية',
    'upFolder':       '.. (المجلد الأعلى)',
    'accessError':    'خطأ في الوصول',
    'goInternal':     'الذهاب للذاكرة الداخلية',
    'setupWizard':    'معالج الإعداد',
    'setupWizardSub': 'خطوات إعداد سريعة وسهلة',
    'addM3uTitle':    'إضافة قائمة تشغيل M3U',
    'addXtreamTitle': 'تسجيل دخول Xtream Codes',
    'appAndListMgmt': 'إدارة التطبيق وقوائم التشغيل',
    'newPlaylistAdd': 'إضافة قائمة تشغيل جديدة',
    'actions':        'إجراءات',
    'version':        'الإصدار',
    'checkUpdates':   'التحقق من وجود تحديثات',
    'checkingUpdates':'جاري التحقق من وجود تحديثات...',
    'upToDate':       'تطبيقك محدث.',
    'active':         'نشط',
    'selectSource':   'حدد مصدر قائمة التشغيل',
    'm3uSub':         'تحميل عبر عنوان الويب',
    'xtreamSub':      'تسجيل الدخول بالمستخدم وكلمة المرور',
    'localSub':       'حدد ملف .m3u على الجهاز',
    'altProtocolTry': 'جاري تجربة بروتوكول بديل...',
    'httpsError':     'خطأ HTTPS! يرجى المحاولة باستخدام http://.',
    'listSavedCount': 'تم حفظ {count} قوائم',
    'm3uUrl':         'رابط M3U',
    'playStore':      'Google Play Store',
    'github':         'GitHub',
    'playlistStats':  'بث مباشر: {tv} | أفلام: {movie} | مسلسلات: {series}',
    'rating':         'التقييم',
    'year':           'السنة',
    'alpha':          'أ-ي',
    'noContentFound': 'لم يتم العثور على محتوى في هذه الفئة.',
    'forSmartTv':     'للتلفاز الذكي',
    'removeFavoriteQ': 'هل تريد إزالة "{name}" من المفضلة؟',
    'removeListQ':     'هل تريد إزالة "{name}" من القائمة؟',
    'sleepTimer':     'مؤقت النوم',
  };
}
