# Windows-to-iOS Migration Resilient Podfile
begin
  require_relative 'Flutter/podhelper'
rescue LoadError
  puts "Uyarı: Flutter/podhelper bulunamadı, manuel kopyalama bekleniyor..."
end

platform :ios, '14.0'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  if defined?(flutter_install_all_ios_pods)
    flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if defined?(flutter_additional_ios_build_settings)
      flutter_additional_ios_build_settings(target)
    end

    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      config.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'
      config.build_settings['CODE_SIGN_IDENTITY'] = ''
      config.build_settings['PROVISIONING_PROFILE'] = ''
      config.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = ''
    end
  end
end
