platform :ios, '14.0'

# Standard Flutter Podfile preamble
podhelper_path = File.expand_path(File.join('..', 'Flutter', 'podhelper.rb'), __FILE__)
if File.exist?(podhelper_path)
  require podhelper_path
else
  # On some environments podhelper.rb might be missing until flutter build is run
  # but standard Flutter apps REQUIRE this.
  # We will try to require it anyway, if it fails, Pod install will fail later.
  require File.expand_path(File.join('..', 'Flutter', 'podhelper.rb'), __FILE__)
end

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Install all Flutter plugin pods
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    # Call Flutter's additional settings if available
    if defined?(flutter_additional_ios_build_settings)
      flutter_additional_ios_build_settings(target)
    end

    target.build_configurations.each do |config|
      # Force disable signing for unsigned/jailbreak builds
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      config.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'
      config.build_settings['CODE_SIGNING_IDENTITY'] = ''
      config.build_settings['PROVISIONING_PROFILE'] = ''
      config.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = ''
    end
  end
end
